import profile from "../assets/images/profile.png";
import thumbnail from "../assets/images/thumbnail.png";
import cards from "../assets/images/cards.png";
import path from "../assets/images/path.png";
import logo from "../assets/images/logo.png";
import logoSmall from "../assets/images/logo-small.png";
import empty from "../assets/images/empty.png";
import forgotPassword from "../assets/images/forgot-password.png";
import accountant from "../assets/images/accountant.png";
import load from "../assets/images/loading.json";
export default { profile, thumbnail, forgotPassword, cards, path, logo, logoSmall, empty, accountant, load };
